### ISSUE TITLE
Unable to load Expo demo.

### ISSUE THREAD

**Issue by jaybowang** [watanabeyu/react-native-qrimage-decoder#3]
Please check out this screenshot.

![img_0428](https://user-images.githubusercontent.com/1948533/40818957-69dba7b4-658c-11e8-9029-b42e5c072d8a.PNG)

**Comment by watanabeyu** [comment]
Hi @jaybowong 
This is expo client(IOS) specification changed.
https://forums.expo.io/t/you-are-not-allowed-to-load-app/9976

If you load expo demo, you download this repository and run example on your environment.
